services:

  autarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autarr
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POCKETBASE_URL=http://pocketbase:8090
      # Add your production environment variables here
      # - ORIGIN=https://yourdomain.com
    depends_on:
      pocketbase:
        condition: service_healthy

  pocketbase:
    image: adrianmusante/pocketbase:0.31
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - pocketbase_data:/pocketbase
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  pocketbase_data:
    name: autarr_pocketbase
