services:

  app:
    image: autarr:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: autarr-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./static:/app/static:ro
      - ./svelte.config.js:/app/svelte.config.js:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      - NODE_ENV=development
      - POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy

  pocketbase:
    image: adrianmusante/pocketbase:0.31
    container_name: pocketbase-dev
    restart: unless-stopped
    volumes:
      - pocketbase_data_dev:/pocketbase
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  autoarr_node_modules_dev:
    name: autarr_node_modules_dev
  pocketbase_data_dev:
    name: autarr_pocketbase_dev
